spring:
    application:
        name: "Crud"
    jpa:
        hibernate:
            ddl-auto: create-drop
        generate-ddl: true
    datasource:
        url: jdbc:h2:file:./src/main/resources/db/database.h2;DB_CLOSE_ON_EXIT=FALSE
